version: "3"

services:
  mariadb:
    image: "mariadb:latest" 
    restart: "always"
    volumes:
      - "./data:/var/lib/mysql/data"
      - "./logs:/var/lib/mysql/logs"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "heticdb"
      MYSQL_USER: "hetic"
      MYSQL_PASSWORD: "hetic"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

  wordpress:
    image: wordpress
    expose:
      - 80
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: heticdb
      WORDPRESS_DB_USER: hetic
      WORDPRESS_DB_PASSWORD: hetic
    volumes:
      - ./wordpress:/var/www/html